// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpqastfkpzbssmewvxqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwcWFzdGZrcHpic3NtZXd2eHFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMzMxNzQsImV4cCI6MjA1NzgwOTE3NH0.IVvn9GDYRnRedPQ8mvfOiCm97UIh6H2CgacDaorD7hY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);