// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdbzhlrmpiowsnbhxlyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkYnpobHJtcGlvd3NuYmh4bHlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MDQzNjgsImV4cCI6MjA1Nzk4MDM2OH0.WliI87zt0pckJTqkIv47VqcPQEP7oNwjsSjLCqsF4lQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);